# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NavDraw' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NavDraw
pod 'lottie-ios'

end
